Adding admin user AFTER enabling authentication
ansible-collections/community.mongodb pull request #536
Opened 2023-01-31 14:17 UTC by alterphp

Adding admin user through localhost exception is only allowed when security authentication is enabled, not before.

Fix #535

2023-02-02 06:38 UTC, rhysmeister commented
@alterphp Thanks for the contribution. This certainly worked the old way, we have tests in https://github.com/ansible-collections/community.mongodb/tree/master/roles/mongodb_auth/molecule/default so I'm not sure why you had a problem before. The new way works anyway and if that's what the manual states I'm inclined to merge this PR. @cognifloyd Any thoughts?

Cheers,

Rhys

2023-02-02 07:42 UTC, alterphp commented
Thanks for the feedback.

The test seems to test that default admin user password works after executing the playbook, which is fine if you do not try to change admin password. 

I'm gonna give a try to a test that changes default admin user to highlight a difference.

2023-02-02 08:16 UTC, rhysmeister commented
The password is just what we use in the test. What I'm saying is that the order, of creating the admin user first, did work.

2023-02-02 13:50 UTC, rhysmeister commented on roles/mongodb_auth/molecule/default/tests/main.yml
> +mongodb_admin_pwd: adminchangedpassword
This file should be put back to what it was. I have spotted the original problem.

2023-02-02 13:50 UTC, rhysmeister commented on roles/mongodb_auth/molecule/default/tests/main.yml
> +mongodb_default_admin_pwd: admin
Note this variable name... **mongodb_default_admin_pwd**

2023-02-02 13:51 UTC, rhysmeister commented on roles/mongodb_auth/molecule/default/tests/test_default.py
> +    pwd = facts.get("mongod_admin_pwd", "adminchangedpassword")
Note the variable name here. This lookup would have always failed and the default value would have been provided. THis line should be
`pwd = facts.get("mongodb_admin_pwd", "admin")`

2023-02-02 16:56 UTC, alterphp commented
I've reverted the last commit. I was trying to test that admin password is well changed because it seems that the testsuite only tests that connection default admin password is OK. In practice, we should always change admin password (the steps that failed in my playbook).

2023-02-02 18:09 UTC, cognifloyd requested changes
No. I would rather not reorder these tasks.

Keep in mind that this should work on:
- a new cluster
- an existing cluster that you are adding auth to
- to validate that an existing cluster has auth enabled

For the last item, note the `create_for_localhost_exception` path. If that path is present, it should skip this task, assuming the admin was already created.

_edit: oh. I see the docs you linked to about Mango 5+_

2023-02-02 18:21 UTC, cognifloyd commented
Will this still work with mongo 4 or 4.4? Or only 5+?

2023-02-02 20:23 UTC, rhysmeister commented
> Will this still work with mongo 4 or 4.4? Or only 5+?

We only test on 5 & 6 now. As far as I know it'll still work. 

@alterphp - I can't actually ysee the problem you originally described. So somethign else must be going on I guess.

2023-02-02 22:03 UTC, alterphp commented
It seems that the process has changed from MongoDB 4.4 to 5.0 :
- Doc for 4.4 explicitly tells to create the admin user first, then enable authentication : https://www.mongodb.com/docs/v4.4/tutorial/enable-authentication/#procedure
- Doc from 5.0 tells to enable authentication, then change admin user, thanks to the localhost exception (that did not exist before) : https://www.mongodb.com/docs/v5.0/core/localhost-exception/
I think the old way had a security disadvantage : a server without authentication might be "stolen" if someone could set the admin user password then enable authentication by gaining a local access.

The problem with the actual task order is that the task **Add mongo admin user with localhost exception** fails because authentication MUST BE enabled in order to change/create any user. The following tasks seems to be applied (I don't understand why), so authentication is enabled. The test checks that authentication is enabled by attempting a connection with admin user with **default** password : this does not prove that the task **Add mongo admin user with localhost exception** is a success, unless the testsuite tries to change the admin password => if attempting to connect admin user with the custom password successes, then it's the proof that localhost exception has been successfully used (and it covers what is considered as a highly recommended practice).

2023-02-03 06:05 UTC, cognifloyd approved these changes
Well, changing the order of the tasks means it won't support mongo 4 then. I need mongo 4 but oh well. That ship has sailed. I guess reordering the tasks is the right thing here.

2023-02-03 08:48 UTC, alterphp commented
Fresh installation will more likely concern MongoDB 5+, and the roles will merely be used for maintenance with MongoDB 4-.

Ideally, it should order the tasks according to the mongodb server version, but I guess an highlighted note in the role could be sufficient.

2023-02-03 09:05 UTC, rhysmeister commented
@cognifloyd  - Your call.
@alterphp - While 4.4 is still an acitvely maintained version it can be a pain supporting everthing. Users of 4.4 can still use an old version of the collection if needed. Soemtimes it's good to get rid of the bagge.

I've opened up two additional PR's related to this...

- https://github.com/ansible-collections/community.mongodb/pull/538
- https://github.com/ansible-collections/community.mongodb/pull/537

2023-02-06 18:31 UTC, rhysmeister commented
Hello @alterphp, I think it's worth nothing here that your change does seem to work with MongoDB  4.4. The mongodb_repository role still had 4.4 for the mongodb_version variable in default/main.yml. I've updated this in the linked PR but the CI here ran using 4.4. I'm assuming it'll be good for 6.0 once merged. I'll merge if there's no further feedback.

2023-02-07 18:54 UTC, merged

2023-02-07 20:29 UTC, alterphp commented
Thanks for the support of this library. I'm new to Ansible and its ecosystem, and I progressively discover the problems it solves, but also how hard it is to solve them !